class Panda1Tester{
   public static void main(String foodDelivery[]){
   
      String foodName ="Mushroom Schezwan noodles";
	  double priceOfFoodName =Panda1.search (foodName);
	  System.out.println("The Price is " +priceOfFoodName);
	  double priceWithGivenQuantity =Panda1.search ("Mushroom Schezwan noodles", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity);
	  System.out.println("-----------------------------");
	  String foodName1 ="Veg Ball Manchurian";
	  double priceOfFoodName1 =Panda1.search (foodName1);
	  System.out.println("The Price is " +priceOfFoodName1);
	  double priceWithGivenQuantity1 =Panda1.search ("Veg Ball Manchurian", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity1);
	  System.out.println("-----------------------------");
	  String foodName2 ="Veg Spring Roll";
	  double priceOfFoodName2 =Panda1.search (foodName2);
	  System.out.println("The Price is " +priceOfFoodName2);
	  double priceWithGivenQuantity2 =Panda1.search ("Veg Spring Roll", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity2);
	  System.out.println("-----------------------------");
	  String foodName3 ="Banana icecream dessert jar";
	  double priceOfFoodName3 =Panda1.search (foodName3);
	  System.out.println("The Price is " +priceOfFoodName3);
	  double priceWithGivenQuantity3 =Panda1.search ("Banana icecream dessert jar", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity3);
	  System.out.println("-----------------------------");
	  String foodName4 ="Chicken lemon pepper";
	  double priceOfFoodName4 =Panda.search (foodName4);
	  System.out.println("The Price is " +priceOfFoodName4);
	  double priceWithGivenQuantity4 =Panda.search ("Chicken lemon pepper", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity4);
	  System.out.println("-----------------------------");
	  String foodName5 ="Chicken Hot N sour soup";
	  double priceOfFoodName5 =Panda1.search (foodName5);
	  System.out.println("The Price is " +priceOfFoodName5);
	  double priceWithGivenQuantity5 =Panda1.search ("Chicken Hot N sour soup", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity5);
	  System.out.println("-----------------------------");
	  String foodName6 ="chicken manchow soup";
	  double priceOfFoodName6 =Panda1.search (foodName6);
	  System.out.println("The Price is " +priceOfFoodName6);
	  double priceWithGivenQuantity6 =Panda1.search ("chicken manchow soup", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity6);
	  System.out.println("-----------------------------");
	  String foodName7 ="veg Manchow soup";
	  double priceOfFoodName7 =Panda.search (foodName7);
	  System.out.println("The Price is " +priceOfFoodName7);
	  double priceWithGivenQuantity7 =Panda.search ("veg Manchow soup", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity7);
	  System.out.println("-----------------------------");
	  String foodName8 ="Chilli Paneer Dry";
	  double priceOfFoodName8 =Panda.search (foodName8);
	  System.out.println("The Price is " +priceOfFoodName8);
	  double priceWithGivenQuantity8 =Panda.search ("Chilli Paneer Dry", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity8);
	  System.out.println("-----------------------------");
	  String foodName9 ="Baby Corn chilli";
	  double priceOfFoodName9 =Panda1.search (foodName9);
	  System.out.println("The Price is " +priceOfFoodName9);
	  double priceWithGivenQuantity9 =Panda1.search ("Baby Corn chilli", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity9);
	  System.out.println("-----------------------------");
	  String foodName10 ="Dragon chicken dry";
	  double priceOfFoodName10 =Panda1.search (foodName10);
	  System.out.println("The Price is " +priceOfFoodName10);
	  double priceWithGivenQuantity10 =Panda1.search ("Dragon chicken dry", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity10);
	  System.out.println("-----------------------------");
	  String foodName11 ="Hunan Chicken dry";
	  double priceOfFoodName11 =Panda1.search (foodName11);
	  System.out.println("The Price is " +priceOfFoodName11);
	  double priceWithGivenQuantity11 =Panda1.search ("Hunan Chicken dry", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity11);
	  System.out.println("-----------------------------");
	  String foodName12 ="Soya chilli";
	  double priceOfFoodName12 =Panda1.search (foodName12);
	  System.out.println("The Price is " +priceOfFoodName12);
	  double priceWithGivenQuantity12 =Panda1.search ("Soya chilli", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity12);
	  System.out.println("-----------------------------");
	  String foodName13 ="Egg Hakka Noodles";
	  double priceOfFoodName13 =Panda1.search (foodName13);
	  System.out.println("The Price is " +priceOfFoodName13);
	  double priceWithGivenQuantity13 =Panda1.search ("Egg Hakka Noodles", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity13);
	  System.out.println("-----------------------------");
	  String foodName14 ="Rainbow sundae";
	  double priceOfFoodName14 =Panda1.search (foodName14);
	  System.out.println("The Price is " +priceOfFoodName14);
	  double priceWithGivenQuantity14 =Panda1.search ("Rainbow sundae", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity14);
	  System.out.println("-----------------------------");
	  String foodName15 ="Milkshake";
	  double priceOfFoodName15 =Panda1.search (foodName15);
	  System.out.println("The Price is " +priceOfFoodName15);
	  double priceWithGivenQuantity15 =Panda1.search ("Milkshake", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity15);
	  System.out.println("-----------------------------");
	  String foodName16 ="Taaka Chinese";
	  double priceOfFoodName16 =Panda1.search (foodName16);
	  System.out.println("The Price is " +priceOfFoodName16);
	  double priceWithGivenQuantity16 =Panda1.search ("Taaka Chinese", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity16);
	  System.out.println("-----------------------------");
	  String foodName17 ="Chinese Wok";
	  double priceOfFoodName17 =Panda1.search (foodName17);
	  System.out.println("The Price is " +priceOfFoodName17);
	  double priceWithGivenQuantity17 =Panda1.search ("Chinese Wok", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity17);
	  System.out.println("-----------------------------");
	  String foodName18 ="Roti";
	  double priceOfFoodName18 =Panda1.search (foodName18);
	  System.out.println("The Price is " +priceOfFoodName18);
	  double priceWithGivenQuantity18 =Panda1.search ("Roti", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity18);
	  System.out.println("-----------------------------");
	  String foodName19 ="Indo-Chinese noodles";
	  double priceOfFoodName19 =Panda1.search (foodName19);
	  System.out.println("The Price is " +priceOfFoodName19);
	  double priceWithGivenQuantity19 =Panda1.search ("Indo-Chinese noodles", 5);
	  System.out.println("The food Price With Quantity " +priceWithGivenQuantity19);
   }
   


}